// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTr6J9RLikkIrBlLEo6PNlwRe-BzTgXc',
    appId: '1:579382632059:web:3686d34937dd60a32a8cde',
    messagingSenderId: '579382632059',
    projectId: 'campusmate-9fd39',
    authDomain: 'campusmate-9fd39.firebaseapp.com',
    storageBucket: 'campusmate-9fd39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlm5W-wpU7JqHAYH_YBY5CXn9tQKt_YEk',
    appId: '1:579382632059:android:31edc8f4dded73792a8cde',
    messagingSenderId: '579382632059',
    projectId: 'campusmate-9fd39',
    storageBucket: 'campusmate-9fd39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWdN2hOU1KbVvtt_td-rr75o1dPuJe0ek',
    appId: '1:579382632059:ios:3a4ce15044f75f2f2a8cde',
    messagingSenderId: '579382632059',
    projectId: 'campusmate-9fd39',
    storageBucket: 'campusmate-9fd39.firebasestorage.app',
    iosBundleId: 'com.example.collegeStudentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWdN2hOU1KbVvtt_td-rr75o1dPuJe0ek',
    appId: '1:579382632059:ios:3a4ce15044f75f2f2a8cde',
    messagingSenderId: '579382632059',
    projectId: 'campusmate-9fd39',
    storageBucket: 'campusmate-9fd39.firebasestorage.app',
    iosBundleId: 'com.example.collegeStudentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCTr6J9RLikkIrBlLEo6PNlwRe-BzTgXc',
    appId: '1:579382632059:web:496cf1f60ce5bd732a8cde',
    messagingSenderId: '579382632059',
    projectId: 'campusmate-9fd39',
    authDomain: 'campusmate-9fd39.firebaseapp.com',
    storageBucket: 'campusmate-9fd39.firebasestorage.app',
  );
}
